"""empty message

Revision ID: 715d020848a4
Revises: e6e817965251
Create Date: 2023-02-26 18:23:14.062510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '715d020848a4'
down_revision = 'e6e817965251'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.drop_column('password')

    # ### end Alembic commands ###
